# Generated by Django 5.1.1 on 2024-09-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(blank=True, choices=[('1', '1 - STAR'), ('2', '2 - STARS'), ('3', '3 - STARS'), ('4', '4 - STARS'), ('5', '5 - STARS')], max_length=10, null=True),
        ),
    ]
