# Generated by Django 5.1.1 on 2024-09-16 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(blank=True, choices=[('1', '1 - STAR'), ('2', '2 - STARS'), ('3', '3 - STARS'), ('4', '4 - STARS'), ('5', '5 - STARS')], default='1', max_length=10, null=True),
        ),
    ]
