# Generated by Django 5.1.1 on 2024-09-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_date_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(choices=[('1', '1 - STAR'), ('2', '2 - STARS'), ('3', '3 - STARS'), ('4', '4 - STARS'), ('5', '5 - STARS')], default='5', max_length=10),
        ),
    ]
