# Generated by Django 5.1.1 on 2024-09-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_teste_alter_review_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
