# Generated by Django 5.1.1 on 2024-09-16 15:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('sellers', '0002_rename_sellers_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxLengthValidator(10000.0)])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(100)])),
                ('image', models.ImageField(upload_to='products/images/')),
                ('resume', models.TextField()),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genres.genre')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
            ],
        ),
    ]
