# Generated by Django 5.1.1 on 2024-09-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
