# Generated by Django 5.1.1 on 2024-09-24 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(error_messages={'min_value': 'É necessário ao mínimo uma quantidade!'}, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
